
[package]
name = "faith" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Luca Machiedo", "Luca Machiedo <cococry.btw@gmail.com>"]
description = "Faith Instant Messaging Client"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
glow = "0.17.0"
khronos-egl = { version = "6.0.0", features = ["static"] }
wayland-client = "0.31.14"
wayland-egl = "0.32.11"
wayland-protocols = { version = "0.32.12", features = ["client"] }
x11 = { version = "2.21", features = ["xlib", "xlib_xcb"] }
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
