#pragma once

#include "../core/envelopes.h"

#define FAITH_DEVICE_LINK_CODE_SIZE 16

#define FAITH_ENVL_CTS_DEVICE_LINK_RESPONSE_BODY_SIZE                          \
  _FAITH_BODY_SIZE(FAITH_ED25519_SIGNATURE_SIZE /* signature response */ +     \
                   FAITH_DEVICE_ID_SIZE /*device ID new*/)

#define FAITH_ENVL_STC_DEVICE_LINK_REQ_BODY_SIZE                               \
  _FAITH_BODY_SIZE(FAITH_CLIENT_ID_SIZE /* auth ID */ +                        \
                   FAITH_ED25519_PUBLIC_KEY_SIZE /*public key new device */ +  \
                   FAITH_DEVICE_ID_SIZE /* device ID new */ +                  \
                   FAITH_DEVICE_LINK_CODE_SIZE /* code */ +                    \
                   sizeof(uint64_t) /* expires_at_ms*/)

#define FAITH_ENVL_HELLO_BODY_SIZE                                             \
  _FAITH_BODY_SIZE(FAITH_DEVICE_ID_SIZE /* client device id */ +               \
                   FAITH_ED25519_PUBLIC_KEY_SIZE /* client public key */ +     \
                   sizeof(uint64_t) /* client nonce */)

#define FAITH_ENVL_HELLO_CHALLENGE_BODY_SIZE                                   \
  _FAITH_BODY_SIZE(sizeof(uint64_t) /* server nonce */)

typedef struct {
  // Auth ID of the session that wants to link a new device
  faith_client_id_t auth_id;
  uint8_t           public_key_new_device[FAITH_ED25519_PUBLIC_KEY_SIZE];
  faith_device_id_t device_id_new;

  // 128 bit randomly generated verification code
  uint8_t code[FAITH_DEVICE_LINK_CODE_SIZE];

  uint64_t expires_at_ms;
} faith_envl_stc_device_link_req_t;

typedef struct {
  // 64 byte cryptographic response signature
  uint8_t signature_response[FAITH_ED25519_SIGNATURE_SIZE];
  // device_id of the new device to be linked
  faith_device_id_t device_id_new;

} faith_envl_cts_device_link_response_t;

typedef struct {
  // ID of the client device initiating authentication
  faith_device_id_t device_id;

  // ED25519 public key belonging to the client device
  uint8_t public_key[FAITH_ED25519_PUBLIC_KEY_SIZE];

  // Random nonce generated by the client
  uint64_t client_nonce;
} faith_envl_cts_hello_t;

typedef struct {
  // Random nonce generated by the server
  uint64_t server_nonce;
} faith_envl_stc_hello_challenge_t;
